# Numpy

 ## numpy crash course

In [2]:
import numpy as np

In [5]:
np.__version__ # if we want to cerion (__version__)

'1.26.4'

In [6]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

## below code we are converting list to array

In [14]:
! pip install numpy

In [16]:
arr = np.array(my_list)

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(my_list)

list

In [21]:
np. # we are going to learn imp funtions

SyntaxError: invalid syntax (3027227589.py, line 1)

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(3.0)

array([0., 1., 2.])

In [25]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
np.arange(20,10) # 1st argument < 2nd argument,    alsways    (1st>2nd argument) start oindex and end index 

array([], dtype=int32)

In [33]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [34]:
np.arange(-16, 10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [36]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [37]:
np.arange(10,30,5) # step indexing

array([10, 15, 20, 25])

In [43]:
np.zeros(10) # parameter tunning == finntunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(5, dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [45]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [47]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [48]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [53]:
np.twos((2,3)) # twos is not a funtion in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [55]:
rand(3,2)

NameError: name 'rand' is not defined

In [56]:
np.random.rand(5)

array([0.05502125, 0.09355274, 0.33631019, 0.74133839, 0.56974861])

In [57]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [58]:
np.random.rand(3,5)

array([[0.05331615, 0.16784048, 0.21912522, 0.07931743, 0.45024834],
       [0.43218427, 0.07428041, 0.39192709, 0.01569284, 0.56336142],
       [0.59753452, 0.10287336, 0.56052521, 0.20420777, 0.02398502]])

In [59]:
np.random.rand((3,5),dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [65]:
np.random.randint(4,6)

4

In [68]:
np.random.randint(2,20)

10

In [70]:
np.random.randint(0,1)

0

In [72]:
np.random.randint(2,20,4)

array([11,  6, 10, 14])

In [73]:
np.random.randint(2,20,4,7)

TypeError: Cannot interpret '7' as a data type

In [74]:
np.random.randint(10,20,5)

array([10, 18, 16, 10, 19])

In [78]:
np.random.randint(10,40,(10,10))

array([[37, 39, 17, 26, 29, 27, 10, 34, 30, 30],
       [33, 16, 28, 38, 25, 20, 28, 21, 28, 23],
       [21, 38, 26, 32, 36, 19, 34, 34, 12, 34],
       [30, 25, 12, 21, 15, 16, 34, 17, 22, 30],
       [39, 36, 13, 27, 34, 33, 36, 33, 14, 11],
       [29, 36, 15, 14, 21, 32, 10, 18, 26, 27],
       [33, 32, 20, 33, 29, 33, 30, 35, 10, 23],
       [16, 29, 32, 26, 13, 26, 13, 29, 28, 39],
       [17, 27, 23, 11, 20, 35, 26, 21, 36, 30],
       [22, 37, 22, 34, 39, 30, 26, 15, 18, 22]])

In [79]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [82]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# slicing in matrix

In [84]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [85]:
type(b)

numpy.ndarray

In [86]:
b

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [87]:
b[:]

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [88]:
b[1:3]  #print the row from 1 to 3

array([[18, 17, 12, 14],
       [16, 13, 10, 15]])

In [89]:
b

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [91]:
b[1,2] # print the 1st row and 2 colom element

12

In [92]:
b[1,3]

14

In [93]:
b[1,-1]

14

In [94]:
b

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [95]:
b[2:3]

array([[16, 13, 10, 15]])

In [99]:
b[0:-2]   # this is backward slicing

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15]])

In [100]:
b[0,2]

10

In [101]:
b

array([[15, 17, 10, 11],
       [18, 17, 12, 14],
       [16, 13, 10, 15],
       [11, 16, 12, 16],
       [14, 18, 18, 10]])

In [102]:
b[-5,-3]

17

In [103]:
b[-4,2]

12

#  Operation

In [106]:
a = np.random.randint(10,20,10)
a

array([18, 11, 19, 17, 11, 14, 10, 11, 19, 17])

In [107]:
# init constructer
# in python there are two important concepts
# 1st is name 
# 2nd is INIT

In [108]:
id(a)

2083617960560

In [109]:
__name__

'__main__'

In [110]:
arr

array([0, 1, 2, 3, 4, 5])

In [113]:
arr2 = np.random.randint(0,100,(10,10))   # 10x10 matrix

In [114]:
arr2

array([[86, 32, 44, 73, 58, 44, 93, 60, 48, 29],
       [86,  9,  2, 70, 69, 75, 89, 99, 91, 65],
       [59, 12,  2, 46, 73,  0, 47, 33, 13, 81],
       [23, 40,  0, 97, 56, 69, 95, 51, 63, 68],
       [23,  2, 84,  9, 98, 30, 29, 55, 23, 55],
       [29, 18, 77, 70,  5, 37, 94, 60, 49, 36],
       [31, 41, 74, 46, 49,  7, 20, 36, 42, 72],
       [78,  0, 89, 82, 58, 78,  9, 96,  1, 36],
       [ 1, 45, 55, 42, 22, 41, 65, 78, 54, 16],
       [66, 58, 57, 31, 48, 82, 30, 67, 14, 72]])

In [115]:
arr[:4]

array([0, 1, 2, 3])

In [116]:
 arr

array([0, 1, 2, 3, 4, 5])

In [117]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])